CREATE TABLE ONGs (
	Id INTEGER PRIMARY KEY,
	Email TEXT NOT NULL UNIQUE,
	Senha TEXT NOT NULL,
	Nome TEXT NOT NULL,
	CNPJ TEXT NOT NULL,
	Categoria TEXT NOT NULL,
	Missao TEXT NOT NULL,
	Acoes TEXT NOT NULL, 
	Causa TEXT NOT NULL
)

CREATE TABLE Voluntarios (
	VolunId INTEGER PRIMARY KEY,
	VolunEmail TEXT NOT NULL UNIQUE,
	VolunSenha TEXT NOT NULL,
	VolunNome TEXT NOT NULL,
	VolunCPF TEXT NOT NULL,
	VolunDataNascimento TEXT NOT NULL
)

CREATE TABLE ONGVoluntarios (
	ONGVolunId INTEGER PRIMARY KEY AUTOINCREMENT,
	OngId INTEGER NOT NULL,
	VoluntarioId INTEGER NOT NULL,
	VoluntarioAprovado INTEGER NOT NULL,
	FOREIGN KEY (OngId) REFERENCES ONGs(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (VoluntarioId) REFERENCES Voluntarios(Id)
		ON DELETE CASCADE
)